server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411  #监控放到哪里
    sleuth:
      sampler:
        # 采样值介于0 到 1之间，1表示全部采集
        probability: 1
eureka:
  client:
    #表示是否将服务注册进eurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，三节点无所谓。集群必须设置为true才能配合rabbon负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: consumer80 #服务注册到注册中心所显示的名称   用到了pom文件中的spring-boot-starter-web 和 spring-boot-starter-actuator 结合注解
    prefer-ip-address: true #访问路径可以显示Ip地址