server:
  port: 80
eureka:
  client:
    register-with-eureka: true #这里不把feign注册进eureka服务上了，feign只是一个客户端
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

#设置feign超时时间
ribbon:
  #指的建立连接所用的时间，适用于网络状况正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接之后，从服务器上读取到可用资源的时间
  ConnectTimeout: 5000
logging:
  level:
    #日志以什么级别监控那个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
