server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    druid:
      driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包  org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 879328127

eureka:
  client:
    #表示是否将服务注册进eurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，三节点无所谓。集群必须设置为true才能配合rabbon负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002 #服务注册到注册中心所显示的名称   用到了pom文件中的spring-boot-starter-web 和 spring-boot-starter-actuator 结合注解
    prefer-ip-address: true #访问路径可以显示Ip地址
#    lease-renewal-interval-in-seconds: 20 #eureka客户端向eureka发送心跳间隔的时间 默认为30秒
#    lease-expiration-duration-in-seconds: 40 #eureka服务端在接收到最后一次心跳后等待的时间上限，默认为90秒，单位秒，超时就剔除

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
